name: Trigger test suite

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  go-test:
    name: Run tests defined for the project
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-file: go.sum

      - name: Install go modules
        if: steps.go.outputs.cache-hit != 'true'
        run: go mod download

      - name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Trigger test suite
        run: |
          go test --short -v --covermode=atomic --coverprofile=coverage.out --coverpkg=./... ./...

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          name: ${{ github.event.repository.name }}
          verbose: true

  editorconfig:
    name: Run editorconfig checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.2
        with:
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig checker against the repo
        run: editorconfig-checker
